services:
  _defaults:
    autowire: true
    autoconfigure: true

  ###########################################################
  # Import Populator (YamlExportPage -> Page)
  ###########################################################
  Neusta\Pimcore\ImportExportBundle\Documents\Import\PageImportPopulator: ~

  Neusta\Pimcore\ImportExportBundle\Documents\Import\PageImporter:
    arguments:
      $yamlToPageConverter: '@neusta_pimcore_import_export.import_page'

  ###########################################################
  # Export Converter (Document -> YamlExportPage)
  ###########################################################
  neusta_pimcore_import_export.export_document:
      class: Neusta\Pimcore\ImportExportBundle\Documents\Export\Converter\DocumentTypeStrategyConverter
      arguments:
        $type2ConverterMap:
          Pimcore\Model\Document\Page: '@neusta_pimcore_import_export.export_page'
          Pimcore\Model\Document\Snippet: '@neusta_pimcore_import_export.export_page_snippet'
          Pimcore\Model\Document\Folder: '@neusta_pimcore_import_export.export_folder'


  ###########################################################
  # Export Populator (Page -> YamlExportPage)
  ###########################################################
  neusta_pimcore_import_export.page.editables.populator:
    class: Neusta\ConverterBundle\Populator\ArrayConvertingPopulator
    arguments:
      $converter: '@neusta_pimcore_import_export.editable_converter'
      $sourceArrayPropertyName: 'editables'
      $targetPropertyName: 'editables'

  neusta_pimcore_import_export.page.property.language.populator:
    class: Neusta\Pimcore\ImportExportBundle\PimcoreConverter\Populator\PropertyBasedMappingPopulator
    arguments:
      $propertyKey: 'language'
      $targetProperty: 'language'
      $skipNull: true

  neusta_pimcore_import_export.page.property.navigation_title.populator:
    class: Neusta\Pimcore\ImportExportBundle\PimcoreConverter\Populator\PropertyBasedMappingPopulator
    arguments:
      $propertyKey: 'navigation_title'
      $targetProperty: 'navigation_title'
      $skipNull: true

  neusta_pimcore_import_export.page.property.navigation_name.populator:
    class: Neusta\Pimcore\ImportExportBundle\PimcoreConverter\Populator\PropertyBasedMappingPopulator
    arguments:
      $propertyKey: 'navigation_name'
      $targetProperty: 'navigation_name'
      $skipNull: true

  ###########################################################
  # Export Populator (Editable -> YamlExportEditable)
  ###########################################################
  neusta_pimcore_import_export.editable.data.populator:
    class: Neusta\Pimcore\ImportExportBundle\Documents\Export\Populator\EditableDataPopulator

