###########################################################
# Neusta Converter Bundle
###########################################################
neusta_converter:
  converter:
    ###########################################################
    # Export Converter (Document -> Page)
    ###########################################################
    neusta_pimcore_import_export.export_document:
      target: Neusta\Pimcore\ImportExportBundle\Model\Document\Document
      populators:
        - Neusta\Pimcore\ImportExportBundle\Populator\IdsPopulator
        - neusta_pimcore_import_export.document.properties.populator
      properties:
        key: ~
        type: ~
        published: ~
        path: ~

    neusta_pimcore_import_export.export_folder:
      target: Neusta\Pimcore\ImportExportBundle\Model\Document\Folder
      populators:
        - Neusta\Pimcore\ImportExportBundle\Populator\IdsPopulator
        - neusta_pimcore_import_export.document.properties.populator
      properties:
        key: ~
        type: ~
        published: ~
        path: ~

    neusta_pimcore_import_export.export_page_snippet:
      target: Neusta\Pimcore\ImportExportBundle\Model\Document\PageSnippet
      populators:
        - Neusta\Pimcore\ImportExportBundle\Populator\IdsPopulator
        - neusta_pimcore_import_export.page_snippet.controller.populator
        - neusta_pimcore_import_export.page_snippet.editables.populator
        - neusta_pimcore_import_export.document.properties.populator
      properties:
        key: ~
        type: ~
        published: ~
        path: ~

    neusta_pimcore_import_export.export_page:
      target: Neusta\Pimcore\ImportExportBundle\Model\Document\Page
      populators:
        - Neusta\Pimcore\ImportExportBundle\Populator\IdsPopulator
        - neusta_pimcore_import_export.page_snippet.controller.populator
        - neusta_pimcore_import_export.page_snippet.editables.populator
        - neusta_pimcore_import_export.page.title.populator
        - neusta_pimcore_import_export.document.properties.populator
      properties:
        key: ~
        type: ~
        published: ~
        path: ~

    neusta_pimcore_import_export.editable_converter:
      target: Neusta\Pimcore\ImportExportBundle\Model\Document\Editable
      populators:
        - neusta_pimcore_import_export.editable.data.populator
      properties:
        type: ~
        name: ~

    neusta_pimcore_import_export.property_converter:
      target: Neusta\Pimcore\ImportExportBundle\Model\Property
      populators:
        - Neusta\Pimcore\ImportExportBundle\Populator\PropertyValuePopulator
      properties:
        key: name
        type: ~

services:
  _defaults:
    autowire: true
    autoconfigure: true

  ###########################################################
  # Export Converter (Document -> Page)
  ###########################################################
  neusta_pimcore_import_export.strategy.export_document:
    class: Neusta\Pimcore\ImportExportBundle\Converter\TypeStrategyConverter
    arguments:
      $typeToConverterMap:
        Pimcore\Model\Document\Page: '@neusta_pimcore_import_export.export_page'
        Pimcore\Model\Document\PageSnippet: '@neusta_pimcore_import_export.export_page_snippet'
        Pimcore\Model\Document\Folder: '@neusta_pimcore_import_export.export_folder'
        Pimcore\Model\Document: '@neusta_pimcore_import_export.export_document'

  ###########################################################
  # Export Populator (Page -> Page)
  ###########################################################
  Neusta\Pimcore\ImportExportBundle\Populator\IdsPopulator: ~

  neusta_pimcore_import_export.page.title.populator:
    class: Neusta\ConverterBundle\Populator\PropertyMappingPopulator
    arguments:
      $sourceProperty: title
      $targetProperty: title

  neusta_pimcore_import_export.page_snippet.controller.populator:
    class: Neusta\ConverterBundle\Populator\PropertyMappingPopulator
    arguments:
      $sourceProperty: controller
      $targetProperty: controller

  neusta_pimcore_import_export.page_snippet.editables.populator:
    class: Neusta\ConverterBundle\Populator\ArrayConvertingPopulator
    arguments:
      $converter: '@neusta_pimcore_import_export.editable_converter'
      $sourceArrayPropertyName: 'editables'
      $targetPropertyName: 'editables'

  neusta_pimcore_import_export.page.property.language.populator:
    class: Neusta\Pimcore\ImportExportBundle\PimcoreConverter\Populator\PropertyBasedMappingPopulator
    arguments:
      $propertyKey: 'language'
      $targetProperty: 'language'
      $skipNull: true

  neusta_pimcore_import_export.document.properties.populator:
    class: Neusta\ConverterBundle\Populator\ArrayConvertingPopulator
    arguments:
      $converter: '@neusta_pimcore_import_export.property_converter'
      $sourceArrayPropertyName: 'properties'
      $targetPropertyName: 'properties'

  ###########################################################
  # Export Populator (Editable -> YamlEditable)
  ###########################################################
  neusta_pimcore_import_export.editable.data.populator:
    class: Neusta\Pimcore\ImportExportBundle\Populator\EditableDataPopulator

  Neusta\Pimcore\ImportExportBundle\Populator\PropertyValuePopulator: ~
