###########################################################
# Neusta Converter Bundle
###########################################################
neusta_converter:
  converter:
    ###########################################################
    # Export Converter (Pimcore Asset -> Folder)
    ###########################################################
    neusta_pimcore_import_export.export_element:
      target: Neusta\Pimcore\ImportExportBundle\Model\Element
      populators:
        - Neusta\Pimcore\ImportExportBundle\Populator\IdsPopulator
      properties:
        key: ~
        type: ~
        path: ~

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Neusta\Pimcore\ImportExportBundle\Populator\IdsPopulator: ~
