neusta_pimcore_import_export_page_export:
    resource: '../../src/Controller/Admin/PageExportController.php'
    type: attribute
    options:
        expose: true

neusta_pimcore_import_export_page_import:
    resource: '../../src/Controller/Admin/PageImportController.php'
    type: attribute
    options:
        expose: true
