neusta_pimcore_import_export_page_export:
    resource: '../../src/Controller/Admin/ExportDocumentsController.php'
    type: attribute
    options:
        expose: true

neusta_pimcore_import_export_page_import:
    resource: '../../src/Controller/Admin/ImportDocumentsController.php'
    type: attribute
    options:
        expose: true
